kind: pipeline
name: default

steps:

- name: master
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ohko/pm
